### PR TITLE
The HTTP clients should not read the body with HEAD method.

### PR DESCRIPTION
**Pull request by haproxyFred**

### CODE REVIEW

**Comment by bsdphk** [comment]
I think I understand what you want here, and it is probably a good idea, and we still have

    rx{req|resp}{hdrs|body}

when we want to be very precise.

But part of the patch is missing, right ?

**Comment by haproxyFred** [comment]
Yes. A part of the patch was missing. Do not know what happened. 1d777a commit should be taken with 75d5ef.

**Comment by bsdphk** [comment]
Ehh, that doesn't look right either?

I'm not really a git/github wizard, but it looks like you need a rebase or something ?

**Comment by haproxyFred** [comment]
Well, now this branch compiles after committing this: https://github.com/vtest/VTest/pull/7/commits/1d777a36f2fce2a5f5a662d96b20a57ae4f22a77

**Comment by haproxyFred** [comment]
If you prefer I can create a new clean pull request.

**Comment by bsdphk** [comment]
Yes, but if you select "Files Changed" at the top, all the recent commits are there also... ?

BTW: This is where I always end up blowing my git tree away, starting over...

**Comment by haproxyFred** [comment]
Yes I see all your the recent commits.
I have merged them in this branch before adding a new commit to fix the compilation issue.
Anyway I am going to create a new clean pull request and. I will close this one just after having written this comment.

**Pull request closed without merging**
