### PR TITLE
build fixes when running convert.sh

### PR DESCRIPTION
**Pull request by haproxyFred**

### CODE REVIEW

**Comment by haproxyFred** [comment]
ebb3bf3 fixes these issues:

src/vtc_process.c: In function ‘process_start’:
src/vtc_process.c:652:11: warning: implicit declaration of function ‘posix_openpt’ [-Wimplicit-function-declaration]
  master = posix_openpt(O_RDWR|O_NOCTTY);
           ^~~~~~~~~~~~
In file included from src/vtc.h:41:0,
                 from src/vtc_process.c:49:
src/vtc_process.c:654:5: warning: implicit declaration of function ‘grantpt’ [-Wimplicit-function-declaration]
  AZ(grantpt(master));
     ^
lib/vas.h:61:8: note: in definition of macro ‘assert’
  if (!(e)) {       \
        ^
src/vtc_process.c:654:2: note: in expansion of macro ‘AZ’
  AZ(grantpt(master));
  ^~
src/vtc_process.c:655:5: warning: implicit declaration of function ‘unlockpt’ [-Wimplicit-function-declaration]
  AZ(unlockpt(master));
     ^
lib/vas.h:61:8: note: in definition of macro ‘assert’
  if (!(e)) {       \
        ^
src/vtc_process.c:655:2: note: in expansion of macro ‘AZ’
  AZ(unlockpt(master));
  ^~
src/vtc_process.c:656:14: warning: implicit declaration of function ‘ptsname’ [-Wimplicit-function-declaration]
  slavename = ptsname(master);
              ^~~~~~~
src/vtc_process.c:656:12: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  slavename = ptsname(master);
            ^
lib/vfil.c: In function ‘VFIL_fsinfo’:
lib/vfil.c:198:16: error: storage size of ‘fsst’ isn’t known
  struct statfs fsst;
                ^~~~
lib/vfil.c:200:6: warning: implicit declaration of function ‘fstatfs’ [-Wimplicit-function-declaration]
  if (fstatfs(fd, &fsst))
      ^~~~~~~

**Comment by bsdphk** [comment]
I have cherry picked the non-config.h parts of this in a separate commit.

The reason I don't copy config.h over, is that I would really like to avoid getting tangled in autocrap here, so I am interested in what the relevant #defines are in your config.h and on what platform that is ?

**Comment by haproxyFred** [comment]
Here is my config.h. I have changed the .h extension to .txt to please GitHUB file uploader.
My platform is Linux with GLIBC 2.24 and GCC 6.3.0.

$ uname -a
Linux fl-haproxy 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux

[config.txt](https://github.com/vtest/VTest/files/2648310/config.txt)

**Comment by nigoroll** [comment]
not directly related, but FTR: the issue I noticed when trying to use vtest as a varnish-cache submodule was that the vtest `config.h` overrode the varnish-cache `config.h`, see
https://github.com/vtest/VTest/pull/2/commits/2d8159e2b37bf1f6b1efb6ad88fd91c4b1255dfd

For a linux setup, I think the important defines are this bit from the autocrappy config.h:

```
* Enable extensions on AIX 3, Interix.  */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
/* Enable threading extensions on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
```

**Comment by haproxyFred** [comment]
A filtered version:

$ grep -v '^\/\*\|^$\|\*/$' config.h
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CURSES_H 1
#define HAVE_DAEMON 1
#define HAVE_DLFCN_H 1
#define HAVE_ENDIAN_H 1
#define HAVE_EPOLL_CTL 1
#define HAVE_FALLOCATE 1
#define HAVE_FNMATCH 1
#define HAVE_FNMATCH_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_LIBDL 1
#define HAVE_LIBNSL 1
#define HAVE_LIBREADLINE 1
#define HAVE_LIBRT 1
#define HAVE_MEMORY_H 1
#define HAVE_NANOSLEEP 1
#define HAVE_NCURSES_H 1
#define HAVE_PTHREAD 1
#define HAVE_PTHREAD_PRIO_INHERIT 1
#define HAVE_PTHREAD_SETNAME_NP 1
#define HAVE_READLINE_HISTORY 1
#define HAVE_READLINE_HISTORY_H 1
#define HAVE_READLINE_READLINE_H 1
#define HAVE_SIGALTSTACK 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_SYS_PERSONALITY_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_VFS_H 1
#define HAVE_TCP_FASTOPEN 1
#define HAVE_TCP_KEEP 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define PACKAGE "varnish"
#define PACKAGE_BUGREPORT "varnish-dev@varnish-cache.org"
#define PACKAGE_NAME "Varnish"
#define PACKAGE_STRING "Varnish trunk"
#define PACKAGE_TARNAME "varnish"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "trunk"
#define SO_RCVTIMEO_WORKS 1
#define SO_SNDTIMEO_WORKS 1
#define STDC_HEADERS 1
#define USE_PCRE_JIT 1
#ifndef _ALL_SOURCE
#define _ALL_SOURCE 1
#endif
#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif
#ifndef _POSIX_PTHREAD_SEMANTICS
#define _POSIX_PTHREAD_SEMANTICS 1
#endif
#ifndef _TANDEM_SOURCE
#define _TANDEM_SOURCE 1
#endif
#ifndef \_\_EXTENSIONS\_\_
#define \_\_EXTENSIONS\_\_ 1
#endif
#define VCC_CC "exec gcc -g -O2 -Wall -Werror -Wno-error=unused-result -pthread -fpic -shared -Wl,-x -o %o %s"
#define VERSION "trunk"
#ifndef _DARWIN_USE_64_BIT_INODE
#define _DARWIN_USE_64_BIT_INODE 1
#endif

**Comment by bsdphk** [comment]
Convert.sh is really only meant for me to run, to see what differences exist between VTest and Varnish-Cache.

I belive the recent Makefile changes have made this ticket obsolete

**Pull request closed without merging**
